### PR TITLE
feat: enforce import sorting

### PR DESCRIPTION
**Pull request by dbasilio**
BREAKING CHANGE: Updating to the new version (assuming this is merged) will cause significant changes in consumers of the package. Those changes should be cosmetic, but will still likely produce a significant number of changes

Based on discussions internally, a lot of PR comments were being posted about import sorting, or member sorting, and those are the types of bikeshedding we don't want to deal with. Even if we're not 100% happy with the results of the automatic sorting, it's better than having to add comments to every PR about sorting.

### CODE REVIEW

**Comment by msrose** [comment]
I actually hate import sorting and think it's a symptom of a codebase with too many large files. Sorting only becomes useful when you have dozens of imports, and if you have dozens of imports your file is too big. If your files are regular-sized, import sorting is just a nuisance and provides no real benefit I've ever experienced.

Would like to seek broader opinions - can you socialize this PR in front-end-club and maybe even elsewhere on slack?

**Comment by dbasilio** [comment]
@msrose I actually tend to agree with you. I think as long as the imports are at least somewhat consistent within a file, I don't particularly care about the ordering.

The issue is that different devs at Top Hat all have different opinions on what the rules of sorting should be, and are commenting on PRs to enforce their preferred sorting algorithm. I basically don't care what the sorting algorithm is, as long as there is one, so that we never have to talk/think about it.

**Comment by noahnu** [comment]
> import sorting is just a nuisance and provides no real benefit I've ever experienced

It provides the same benefit as enforcing order of object properties. It reduces the differences between code written by different developers. Ideally, if we're using sufficient lint rules, and you give 2 developers a task, they should produce almost identical code. It creates uniformity in the codebase.

**Comment by Benmiller313** [comment]
Generally agree that huge import lists is a code smell but I'm not sure we'd ever act on it. If we don't put this lint rule will we see more people encouraged to break up files in to more manageable pieces or will we just continue to not pay much mind to our imports?

**Comment by msrose** [comment]
I'm in favour of enabling on a case-by-case basis in repos where it's an issue, but globally in all projects I am less inclined 😛 And also working towards a culture where we don't make PR comments for things that are statically analyzable, those comments should be replaced in favour of enabling a linting rule in the repo itself.

**Comment by msrose** [comment]
Speaking of sorting object properties, I hate that even more for some of the same reasons 😛In the case of object properties it doesn't always make sense to sort alphabetically, like in the case of
```js
{
    small: '5px',
    medium: '10px',
    large: '50px'
}
```
so I don't think that's a good comparison. And does uniformity in imports or key order really matter unless you have more than half a dozen? No, because you can understand everything as a whole in the way it was written. I think prettier takes care of everything relevant for code uniformity that is automatable.

**Comment by toryth** [comment]
If it can be automated (which it is) it should be automated. If we decide not to automate it, then there should be no PR comments on the topic, unless it is to say, you have too many imports, and that you should break your stuff up :)

**Comment by msrose** [comment]
Unless anyone has further comments I'll be merging in the next half hour or so, votes are currently +3 -1 
image

**Pull request merged**
